### ISSUE TITLE
Option type should be used with non-zero Height

### ISSUE THREAD

**Issue by soareschen** [informalsystems/ibc-rs#1009]
## Crate

`ibc-rs`

## Summary

Currently the `Height` type uses a special `Height::zero()` value to denote the absence of height value. This causes ad hoc checks of whether a height is zero in various places. We should instead use `Option<Height>` on places where the height value may be optional, and require non-zero value in the `Height` constructor.

## Acceptance Criteria

- Optional height parameters should use `Option<Height>` instead of `Height`.
- Checking of `height == Height::zero()` is replaced with Option matching.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by plafer** [comment]
My only potential concern with this solution is that our `Height` type would no longer be a partially ordered set over its entire domain, which is required in ICS 2, assuming that `None` serves as the zero-element. `Option<Height>` would correspond to `Height` in the spec, assuming a proper implementation for `cmp()`. 

However, looking at the code, the zero height is often used as a special value, sometimes even explicitly mentioned in [comments](https://github.com/informalsystems/ibc-rs/blob/6b536c7cee33bb46395f35419e25a8da913e6785/modules/src/core/ics03_connection/msgs/conn_open_try.rs#L41). This is confusing to me as I don't see any mention in the spec that the zero height should be treated differently.

What am I missing here? I definitely agree that `Option<Height>` + pattern matching should be used for treating the special case. However, I'm concerned that we might be introducing a bug w.r.t a "real" `height == 0` state, since I don't understand how the zero height is used in the implementation, and how that relates back to the spec.

**Comment by hu55a1n1** [comment]
Note that `Height::zero()` can also mean `latest` height, especially in the context of Tendermint RPC -> https://docs.tendermint.com/master/rpc/#/Info/block

**Comment by romac** [comment]
We should perhaps encode this across the whole codebase as 

```rust
enum Height {
  Latest,
  Specific(u64)
}
```

and then only convert `Height::Latest` to `0` or `None` on a case-by-case basis, depending on what the underlying API expects to mean "latest height".

**Comment by plafer** [comment]
It seems like a bunch of events use the zero height as well:

1. `IbcEvent::OpenInitChannel`, `IbcEvent::OpenTryChannel`, etc. use the zero height implicitly by being [constructed with default values](https://github.com/informalsystems/ibc-rs/blob/1aea3cf9f8f9f643544a5cfaf4e5794469524bbc/modules/src/core/ics04_channel/handler/chan_open_try.rs#L142) for all fields but the channel id.
2. `IbcEvent::ReceivePacket` is [constructed with `Height::zero()` explicitly](https://github.com/informalsystems/ibc-rs/blob/1aea3cf9f8f9f643544a5cfaf4e5794469524bbc/modules/src/core/ics04_channel/handler/recv_packet.rs#L130), which @adizere suggested should be replaced with current chain height.

It seems to me that these should all use chain height from `ChannelReader::host_height()`, right?

**Comment by soareschen** [comment]
For context, I tried to solve this by implementing a `NonZeroHeight` type [here](https://github.com/informalsystems/ibc-rs/pull/1011/files#diff-bb3506b36cf8617a86655f2786f61e1e44f32108beabd59d760a65bad73905f4R22-R60) in #1011.

The plan was to split the refactoring in multiple phases: 

1. All places that originally used `Height` do not need to be edited to become `Option<Height>`. 
2. We can incrementally refactor functions that accept `Height` to instead use `NonZeroHeight`. 
3. After all use of `Height` are eliminated, we can remove `Height` and then rename `NonZeroHeight` to `Height`.

**Comment by hu55a1n1** [comment]
> Yep, at least that's my understanding. @hu55a1n1 what do you think?

It is not clear to me what the event height means from the modules' perspective, because it seems like ibc-go doesn't include a `height` attribute in the events that it emits. From what I can see, the height is only used by the relayer code to determine the height of the block which included the tx that emitted this event. So I am not sure if we want to keep the height as part of the `IbcEvent` itself. Furthermore, the event height is only set by the relayer code that deals with events. We also have Tendermint RPC event variants in the `IbcEvent` enum and maybe we should separate them from core IBC events in the future. (Related https://github.com/informalsystems/ibc-rs/issues/1288)

> Moreover, we should stop building events via the Attributes struct and its Default instance, but rather
a) define explicitly what data each event carry in the event struct directly
b) use a constructor to build the event

💯

**Comment by plafer** [comment]
> > Yep, at least that's my understanding. @hu55a1n1 what do you think?
> 
> It is not clear to me what the event height means from the modules' perspective, because it seems like ibc-go doesn't include a `height` attribute in the events that it emits. From what I can see, the height is only used by the relayer code to determine the height of the block which included the tx that emitted this event. So I am not sure if we want to keep the height as part of the `IbcEvent` itself. Furthermore, the event height is only set by the relayer code that deals with events. We also have Tendermint RPC event variants in the `IbcEvent` enum and maybe we should separate them from core IBC events in the future. (Related #1288 & #1909)
> 
> > Moreover, we should stop building events via the Attributes struct and its Default instance, but rather
> > a) define explicitly what data each event carry in the event struct directly
> > b) use a constructor to build the event
> 
> 💯

Discussion relevant to #2043

**Comment by plafer** [comment]
FYI I'll wait on #2044 to be merged before I start working on this one to avoid merge conflicts.
