### ISSUE TITLE
Figure out if we can design protocols that allows identifiers reuse

### ISSUE THREAD

**Issue by milosevic** [informalsystems/ibc-rs#107]

**Comment by milosevic** [comment]
@cwgoes

**Comment by cwgoes** [comment]
Aye. This is not urgent - and may not even be worth the complexity - but just to note:

At the moment, once connection & channel identifiers are reserved, they can never be freed again, even when the connections or channels are closed. This is the case because we need to ensure that handshake steps or packets cannot be replayed - once packets or handshake steps are sent once, the proofs will validate later, so if identifiers were naively reused handshake steps or un-timed-out packets could potentially be relayed.

Handshake step replay and packet replay can both be prevented in another way by ensuring bounds on timeouts, and allowing identifiers to be reused after handshake steps or packets are guaranteed to have timed-out - e.g. if channels allow only packets with a maximum of 500 blocks in the future timeouts, then once 500 blocks have passed after a channel is closed, the identifier can safely be reused. This would require nontrivial changes to the IBC specification, but is the only safe way I can think of of allowing identifier reuse, if we want that feature.

**Comment by adizere** [comment]
At the moment, in `ibc-rs` we consider a connection identifier valid if it consists of at least `10` and at most `20` characters ([ref](https://github.com/informalsystems/ibc-rs/blob/master/modules/src/ics24_host/validate.rs#L61)). This is not practically infinite, but accommodates for a pretty huge universe of identifiers. That being said, it's unclear if this feature is useful.

Just to note that a feature that would be more important is garbage collection. Intuitively, if we have the assumption with the "500 block timeouts", then we can garbage collect data (e.g., closed connection & closed channel identifiers) safely. If we can garbage collect safely, that's an essential step towards getting the "identifier reuse" feature.

**Comment by adizere** [comment]
Closing: this is a "nice to have feature" but probably depends on protocol assumptions, is further down the road, and is not strictly related to the concerns of this repository.
