### ISSUE TITLE
Dependency on tendermint-rs causes compilation failure

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#113]
## Summary of Bug

Compilation (`cargo build`) on a vanilla clone fails with errors:

```
error[E0433]: failed to resolve: could not find `rpc` in `tendermint`
  --> modules/src/events.rs:11:17
   |
11 | use tendermint::rpc::event_listener::{ResultEvent, TMEventData};
   |                 ^^^ could not find `rpc` in `tendermint`

error[E0433]: failed to resolve: could not find `rpc` in `tendermint`
 --> modules/src/ics02_client/query.rs:2:17
  |
2 | use tendermint::rpc::endpoint::abci_query::AbciQuery;
  |                 ^^^ could not find `rpc` in `tendermint`

error[E0433]: failed to resolve: could not find `rpc` in `tendermint`
 --> modules/src/ics03_connection/query.rs:1:17
  |
1 | use tendermint::rpc::endpoint::abci_query::AbciQuery;
  |                 ^^^ could not find `rpc` in `tendermint`
```

This seems to happen since `tendermint-rs` release 0.14.1, which would explain the error, since this release included a separation of the `rpc` module into its own crate: https://github.com/informalsystems/tendermint-rs/commit/e2335c40b1c5e1f7d47ee28ae5f9cc679730b7a2.

## Version

```
rustc --version
rustc 1.44.1 (c7087fe00 2020-06-17)
```

ibc-rs commit: `commit 7a49bca2c34cb9964c66137a9edaa4c5f7a9b6c1`

## Steps to Reproduce

```
git clone git@github.com:informalsystems/ibc-rs.git
cd ibc-rs
cargo build
```

## Solutions

1. Wherever we use the `tendermint::rpc` create, we need to replace that with `tendermint_rpc`. For instance:
```use tendermint_rpc::event_listener::{ResultEvent, TMEventData};```
instead of
```use tendermint::rpc::event_listener::{ResultEvent, TMEventData};```

Alternatively, for a nicer read `use tendermint_rpc as rpc;`.

2. A quicker -- temporary fix -- would be to rely on a specific release as dependency in our .toml files:

```
tendermint = { git = "https://github.com/informalsystems/tendermint-rs.git", tag = "0.14.0" }
```
____

## For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by liamsi** [comment]
Just chiming in because it's partly my "fault" that we broke out the rpc crate. IMO you should do both: replace existing uses with `tendermint_rpc`, and, refer to a specific version (preferably the latest current version though which is 0.14.1). The first is to fix the compile issues and the latter is to be in control when to upgrade the next time.

**Comment by liamsi** [comment]
Happy to help with the 1st if that is desired.

**Comment by adizere** [comment]
Thanks @liamsi! I didn't think of fix (2) as a "knob" to control upgrades, but that's a very good point. The dependency currently references branch master:

https://github.com/informalsystems/ibc-rs/blob/7a49bca2c34cb9964c66137a9edaa4c5f7a9b6c1/modules/Cargo.toml#L18-L21

There may have been a good reason to code it this way originally, but seems like a certain source of future issues.

> Happy to help with the 1st if that is desired.

Cool, I'll ping you for a PR review.

**Comment by andynog** [comment]
I think I've got it "almost" compiling with a few changes:

You can add a new dependency in **cargo.toml** for the tendermint-rpc like this (under [dependencies])

`tendermint-rpc = { git = "https://github.com/informalsystems/tendermint-rs.git", path = "/rpc", features=["client"] }`

Then as @adizere suggested you replace tendermint::rpc with use tendermint_rpc

But the reason I've said almost is because the client feature in tendermint-rs is not public, so this line in _modules/src/events.rs_ fails saying the module **tendermint_rpc::client is private**.

`use tendermint_rpc::client::event_listener::{ResultEvent, TMEventData}; `

Any reasons to have it private ? 

I think this is where it's declared and it's not pub 

https://github.com/informalsystems/tendermint-rs/blob/master/rpc/src/lib.rs

**Comment by liamsi** [comment]
Do you mind opening a draft PR (with the almost succeeding version)? Just to make sure we aren't missing anything. But yes, it sounds like this should be public on the tednermint side.

**Comment by andynog** [comment]
OK I will submit a PR

**Comment by andynog** [comment]
Submitted draft PR, but build still failing because of client is private in tendermint-rs. I think this might be a good test for the newly refactored crates out of tendermint-rs
