### ISSUE TITLE
Add nix support

### ISSUE THREAD

**Issue by JonathanLorimer** [informalsystems/ibc-rs#1171]
## Crate

All

## Summary

I would love to have nix support for each sub directory, and potentially a top level definition that provides access to all the packages in the sub-directories.

## Problem Definition

The goal of nixifying ibc-rs is that I want to run my own IBC relayer, and the easiest way to spin up infra reliably (IMO) is with nix. Nixifying this repo will make things a bit easier downstream (for me), will facilitate adding this software to nixpkgs (which might make it easier for others to install and use), and might provide some dev-env benefits to the development team if they choose to use nix!

## Proposal

Write a `flake.nix`, `shell.nix`, and `default.nix` for each sub-directory, and potentially a `flake.nix` for the top level project that provides access to the nix derivations of the sub directories.

Here is some documentation on nix and rust if you are interested:
- [NixOS wiki](https://nixos.wiki/wiki/Rust)
- [Article motivating the use of nix](https://shopify.engineering/what-is-nix)
- [Blog post explaining the problem nix solves](https://hadean.com/blog/managing-rust-dependencies-with-nix-part-i/)
- [Example nix project written in rust!](https://github.com/nix-community/lorri)
- [Rust project that was recently nixified](https://github.com/soywod/himalaya)

## Acceptance Criteria

- nixify `modules`
- nixify `relayer`
- nixify `relayer-cli`
- nixify `proto`
- nixify `proto-compiler`
- nixify `telemetry`
- OPTIONALLY: add a nix expression at the top level that conveniently exports all of the sub-directories

I recognize that "nixify" is pretty vague for those who aren't familiar. For an example please see this [PR](https://github.com/informalsystems/ibc-rs/pull/1170)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Hi @JonathanLorimer, thanks for opening this issue and the associated PR.

While having a more reproducible build environment and supporting more people's workflows is definitely valuable, managing and keeping the nix derivations up to date is yet more code to maintain and is therefore one more liability, especially given that none of us on the ibc-rs team aside from @soareschen are familiar with Nix.

Given that we have very limited bandwidth at the moment, I would like to get a better feel for how much maintenance we can expect these Nix derivations to require. Do you have any insights on that, eg. how often must one touch the derivations for a typical Rust project?

As a follow-up, do you know if it's it possible to maintain these derivations in a separate repository? Perhaps by including the ibc-rs repo as a submodule there? This way, we wouldn't burden the ibc-rs team with keeping the derivations up-to-date, but would still provide a nixified ibc-rs, which may lag a bit behind the main repo, but could still be kept up to date by volunteers such as yourself.

/cc @soareschen

**Comment by JonathanLorimer** [comment]
@romac Yeah, this is a common sentiment around the burden of maintaining nix. I can say that I would be interested in maintaining it for the foreseeable future, but I understand that isn't entirely satisfying. There are 4 main benefits I see from adding nix to the `ibc-rs` repo:
 1. `ibc-rs` developers might benefit from a nix environment. You can see on [this line](https://github.com/informalsystems/ibc-rs/pull/1170/files#diff-b32de12ae3e40efcced3e3df0765e4101b7e8b813f56b67b66fdad9dfbdabd9cR91) that things like `cargo` and `cargo-watch` are made available. I could easily add `rust-analyzer` or `rls` or whatever dev dependencies  you need. Also, by providing third-party libraries explicitly in nix (like how `prost-build` requires `protoc`) you can potentially speed up onboarding new devs; new devs don't need to _just know_ they need protobuf, install it via their own package manager, and set the `PROTOC` and `PROTOC_INCLUDE` env var correctly [example](https://github.com/informalsystems/ibc-rs/pull/1170/files#diff-b32de12ae3e40efcced3e3df0765e4101b7e8b813f56b67b66fdad9dfbdabd9cR56-R59).
 2. E2E tests with NixOS testing library (offers fully virtualized integration tests).
```
# test.nix
import <nixpkgs/nixos/tests/make-test-python.nix> ({ pkgs, ... }:
  {
  name = "prometheus-exporter-weather-gov";
  machine = { pkgs, ... }: {
    imports = [ ./service.nix ];
  };
  testScript =
    ''
      start_all()
      machine.wait_for_unit("prometheus-exporter-weather-gov.service")
      machine.wait_for_open_port(5000)
      machine.succeed("curl http://127.0.0.1:5000/")
    '';
})
```
```
$ nix-build ./test.nix
machine: starting vm
machine # [ 3.839794] systemd[1]: Started prometheus-exporter-weather-gov.service.
machine: waiting for TCP port 5000
machine: must succeed: curl http://127.0.0.1:5000/
machine # [ 7.673543] exporter[516]: 127.0.0.1 - - [08/Jun/2021 15:59:49] "GET / HTTP/1.1" 200 -
```
3. It makes the individual pieces of software easier to run, for example `nix-shell --run "compile"` for the ibc-proto-compiler rather than the multi step command in the readme. If I packaged ibc-rs on nixpkgs, then this command wouldn't be available.
4. Its nice to have the constituent ibc libraries be reproducible inputs to the `ibc-relayer-cli`

The other option is I could just package `ibc-rs` on nixpkgs, which is fine, but it loses out on the rust-nix toolchain i.e. integrating with cargo to generate a derivation. It also means that I would probably only packge `ibc-relayer-cli` (which is fine, but misses out on some of the benefits mentioned above).

**Comment by soareschen** [comment]
Thanks for the initative @JonathanLorimer! I have experience in using Nix at my previous work place, and I do think there are advantages for us to support Nix build for ibc-rs. In particular, I think the advantage of using Nix becomes obvious when bundling the relayer CLI with other components in Cosmos, such as different versions of Cosmos SDK. Having such integration with Nix will allow us to have more reproducible end-to-end testing, and in the future even allows relayer operators to run entirely on NixOS.

For us to get there, there are a few challenges that I learned from previous experience which I think needs to be addressed:

### Nix Cache

For a Nix project to be usable to non-Nix users, it is important that any official Nix release must provide an official Cachix store. When I enter the Nix shell in #1170 for the first time, it takes quite a while for Nix to build all the Rust dependencies. The compile time for Rust Nix projects are not as bad as Haskell Nix project, but I think it is still bad user experience to convince people to use Nix when they have to wait for all dependencies to be built.

### CI Integration

To provide proper Nix cache that is up to date, it is also important to automate the caching process via CI build. It is fragile to do ad hoc pushing of Nix cache from local computer. But supporting the Nix cache on CI also requires adequate secret management of the Cachix token, which also requires additional effort.

### Mac Support

It may not be sufficient to only have Linux build of Nix tested, as there is a pretty large number of Mac developers out there. It is frequently a pain to develop the Nix code on Linux or NixOS, then only to find out after release that it is broken on Mac. This can bring bad user experience to the Mac users. And if the Nix build becomes essential to the development workflow, this can block the development process of Mac users. 

For myself, I use Ubuntu and do not have any modern Mac machine with me, and it is very difficult to provide Mac support without a Mac machine. It is also challenging to create CI workflows that support Mac. Even though GitHub Actions allows CI to run on Mac instances, the pricing is too high to be practical for Nix CI builds which can take very long time.

### Handling Pull Requests

A major issue of tightly coupling the Nix project with the main project is that when someone submits a pull request that updates some dependencies, the CI tests using Nix may fail and this in turns block the contributor from being able to merge the PR. Unless everyone is already using Nix, it is difficult to introduce any CI workflow that uses Nix which can potentially block non-Nix users from contributing. On the other hand, if the CI for Nix build is not enabled, new code changes can easily break the existing Nix build and impact the developers using Nix.

### Multi-Project Integration

Nix is most useful in integrating multiple software projects together and provide a reproducible development environment. In our case we would ideally like to have Nix support on at least `ibc-rs`, `tendermint-rs`, `cosmos-sdk`, and `gaiad`. However it is more challenging to require all projects to adopt the same Nix workflow, as different teams are responsible for each project. It would also be challenging to maintain a unified Nix cache with the secret being shared across multiple projects.

Another challenge is that when a sub-project depends on another sub-project, maintaining that dependency on Nix can be pretty tedious. Now with Nix Flakes, the pinned versions are recorded in lock files which is better than before. But it still requires the updated lock file to be committed to the dependent's repository, and this can easily pollute the git commits.

## Better Alternative: Separate Nix Repository

Based on my experience, I feel that the best way to integrate Nix with existing projects is to create separate repositories the focus on the Nix integration itself. In our case, it would be a project like `cosmos.nix` maintained by Informal. With the way Nix works, we can easily import project source files using constructs like `builtins.fetchTarball`. I don't have much experience with Nix flakes, but I believe we should be able to list source repositories as dependency as well.

With a separate repository, all the Nix effort can go in one place without affecting the workflow of the individual projects. There are also ways which we can have two-way integration with the individual projects, so that developers can still enter a Nix shell development environment for each project.

A downside of this approach is that upstream changes can sometimes break the Nix build. But based on my experience, this trade off is still better than forcing everyone to support Nix in one go. With projects like nixpkgs, it is also common practice to fix broken Nix packages downstream instead.

**Comment by JonathanLorimer** [comment]
Hey @soareschen thank you for the thoughtful response.

I think I agree with your assessment. A `cosmos.nix` that encompasses `ibc-rs`, `tendermint-rs`, `cosmos-sdk` and `gaiad` would be ideal.

FWIW I don't think managing a cachix cache and the secrets would be very hard. Domen just introduced API keys, so its actually quite easy. Cachix cache's _are_ a bit pricey though.

I also don't think upstream changes would result in breakages if we went the separate repo route, since with `fetchTarball` and `fetchFromGitHub` you can pin to a rev hash.

I am happy to start working on a separate repo. Would informal be willing to host the repo for visibility?

**Comment by soareschen** [comment]
> I am happy to start working on a separate repo. Would informal be willing to host the repo for visibility?

Sounds good. I have created the [cosmos.nix](https://github.com/informalsystems/cosmos.nix) repository. Feel free to experiment around and submit pull requests over there.

> do you need anything other than ibc-rs to run a relayer? The end goal of this project, for me, is to make it dead simple to spin up a relayer, and the easiest way I know to get something reproducible like that is with nix.

Having the relayer CLI built as Nix packages would be a good start. I also plan to create Nix build for `gaia` so that we can create end-to-end tests that spawn the test chains using Nix. Without that, you have to test the relayer by either spawning the test chains manually, or use the relayer with existing test nets or main nets. Having Docker images build from Nix would also be nice to have.

> FWIW I don't think managing a cachix cache and the secrets would be very hard. Domen just introduced API keys, so its actually quite easy. 

Yes, the API keys from Cachix makes it easier to manage the secrets. There are still some organization overhead of how we want to deal with and rotate the secrets. I am also not too sure of how to prevent the secret from leaking in a public GitHub project, with PRs being able to execute arbitrary code if they are allowed to run on the CI, including stealing the secrets set from GitHub Secrets.

> Cachix cache's are a bit pricey though. The other option is an S3 cache, which is much more work to setup but cheaper. It would be really cool if there was some sort of IPFS or filecoin based nix cache solution.

I think Cachix is free to use for public projects, and we probably don't need too much storage aside from the free storage available. Setting up the Nix cache elsewhere requires too much operational overhead to worth considering IMO.

> I also don't think upstream changes would result in breakages if we went the separate repo route, since with fetchTarball and fetchFromGitHub you can pin to a rev hash.

What I mean is things may break when we update the pinned version to a newer version. It can be common that a new version of package is released, and someone wants to use it immediately in Nix but find that it is broken after updating the lock.

**Comment by JonathanLorimer** [comment]
> Yes, the API keys from Cachix makes it easier to manage the secrets. There are still some organization overhead of how we ? want to deal with and rotate the secrets. I am also not too sure of how to prevent the secret from leaking in a public GitHub project, with PRs being able to execute arbitrary code if they are allowed to run on the CI, including stealing the secrets set from GitHub Secrets.

I think as long as you keep the list of admins small this isn't an issue? I don't think contributors get access to secrets on PRs?
Perhaps I am misunderstanding this: https://github.com/cachix/cachix-action#security

> I think Cachix is free to use for public projects, and we probably don't need too much storage aside from the free storage available. Setting up the Nix cache elsewhere requires too much operational overhead to worth considering IMO.

I believe it is free for up to 5gb of storage, which isn't that much, but is a good starting spot. I am happy to setup the GHA CI workflow, but you will probably have to setup cachix since it will be informal's

---

Thanks for setting up cosmos.nix, I am excited to try and get the ibc-relayer-cli setup!

**Comment by soareschen** [comment]
Ok. Perhaps we can worry about that later on when we have proper Nix release. Let's just focus on the development first and not get distracted by caching.

**Comment by JonathanLorimer** [comment]
@soareschen If you want we can use my personal cachix cache at the beginning. I am not worried about api keys being available in GHA, I can send you an api key over signal if you want.

**Comment by soareschen** [comment]
It is fine, there is no need for that. It is just that I have previously spent a pretty significant amount of time on setting up proper Nix cache on Cachix, and I find the work to be non-trivial. So it is something to consider during the development.

I think we can close this issue now and move further discussion to informalsystems/cosmos.nix.
