### ISSUE TITLE
query connection given connection_id

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/ibc-rs#130]
Given a connection id, query the connection.

Should be able to run this from the relayer CLI.

**Comment by ancazamfir** [comment]
Proto definitions for connection queries and responses (see `ConnectionEnd`, `Counterparty`, etc) are here:
https://github.com/cosmos/cosmos-sdk/tree/master/proto/ibc/connection

**Comment by andynog** [comment]
As per our discussion today, I'll create a proto folder and store the proto files in there following the same structure as the  cosmos sdk proto folder.

**Comment by liamsi** [comment]
BTW, something I forgot to mention but you've probably seen already is that if you want to generate the rust types during build time, you also need a dependency on [`prost-build`](https://docs.rs/prost-build/0.6.1/prost_build/):
```
[build-dependencies]
prost-build = "0.6"
```
and a `build.rs` file. In tendermint-rs we never used that because we never generated the types (this might change in the near future too). Here is an example:
https://github.com/libp2p/rust-libp2p/blob/master/core/build.rs
https://github.com/libp2p/rust-libp2p/blob/master/core/src/keys.proto
https://github.com/libp2p/rust-libp2p/blob/6ad05b0ff1cb11ceec37cb191adb0d13feaceeb4/core/src/lib.rs#L38-L40

**Comment by andynog** [comment]
- Added a new branch **andy/proto**
- Implemented the initial proto files required for the connection. 
- The proto files are in the modules folder. 
- Copied proto files from cosmos-sdk and tendermint repos, but it seems they are not in sync, e.g. a cosmos proto file reference an import from tendermint that was not valid. Noticed the tendermint proto files just had a refactoring a few hours ago. Looks like this proto work on the crates are pretty much in flux for now.
- There's a new build.rs in there that generate the files in the output folder (e.g. /target/debug/build/relayer-modules-[HASH]/ibc.connection.rs).
- Then tried to replace the connections mod (modules/src/ics03_connection/mod.rs) with generated file as per prost_build instructions but got bunch of failures probably because there are dependencies that the original Rust connection had and it's not in the generated proto files. 

Next steps are trying to make it compile again using the new proto generated file. We might need to chat about this. Seems to me that a lot of logic in the proto files are somewhat duplicate with things already implemented in the Rust code.

**Comment by ebuchman** [comment]
Just a note for now let's try to use the minimal amount of proto to get this working. Since this is just the ConnectionEnd we should probably copy over just the pieces we need to query just a ConnectionEnd - I don't think that should have any dependency on Tendermint. If we copy over the full dir we'll have lots of deps but let's try to simplify first to get it working.

**Comment by andynog** [comment]
> Just a note for now let's try to use the minimal amount of proto to get this working. Since this is just the ConnectionEnd we should probably copy over just the pieces we need to query just a ConnectionEnd - I don't think that should have any dependency on Tendermint. If we copy over the full dir we'll have lots of deps but let's try to simplify first to get it working.

I’ve tried to use the minimal as far as I know. There might be more ways to trim possibly. The dependency on tendermint proto is from the cosmos proto, there’s an import for tendermint.crypto.Proof (which the cosmos proto had what it seems an old reference tendermint.crypto.merkle.Proof and I changed to match the new tendermint reorged protos). We should have some discussions on how we want to handle proto files on our side. Thought the idea of using proto in the end was that all implementations used the same interface to prevent mismatches and deserialization issues. But if we’re going to implement our own protos then we can structure for now in a more simplistic way.

**Comment by adizere** [comment]
Regarding the dependency on the Go proto definitions & compiling them:

It seems that the problem with using the [Go-based .proto files](https://github.com/cosmos/cosmos-sdk/tree/master/proto/ibc/connection) is that there are some Go-specific declarations in there. The `gogo` extension is problematic: 

```
message ConnectionEnd {
  option (gogoproto.goproto_getters) = false;
  // connection identifier.
  string id = 1 [(gogoproto.customname) = "ID", (gogoproto.moretags) = "yaml:\"id\""];
  // client associated with this connection.
  string client_id = 2 [(gogoproto.customname) = "ClientID", (gogoproto.moretags) = "yaml:\"client_id\""];
  // opaque string which can be utilised to determine encodings or protocols for
  // channels or packets utilising this connection
  repeated string versions = 3;
  // current state of the connection end.
  State state = 4;
  // counterparty chain associated with this connection.
  Counterparty counterparty = 5 [(gogoproto.nullable) = false];
}
```

Trying to trim out the `gogo` part and see where that leads.

**Comment by adizere** [comment]
While writing the above ^ comment I remembered that there are more "canonical" proto definitions here:

https://github.com/cosmos/ics/blob/master/spec/ics-003-connection-semantics/data-structures.proto

**Comment by liamsi** [comment]
> It seems that the problem with using the Go-based .proto files is that there are some Go-specific declarations in there. The gogo extension is problematic:

Out of curiosity do they err if build with `prost`? It would be good to give that as feedback to the tendermint/sdk team.

**Comment by andynog** [comment]
* Implemented logic that the response can be decode using prost. 
* Error handling is not the best for now, just added something so it could compile need to understand how to do it properly
* There are a few classes that have todo!() that we might need to implement later now that we are deserializing things (e.g. CommitmentPath)

If you want to run this 

* You have to use the andy/proto branch. 
* Get the simapp folder from bucky's branch (https://github.com/informalsystems/ibc-rs/tree/bucky/genesis-data/relayer/tests/support/ibc-test)
* Run `simd --home simapp start`
* On another terminal window got to the ibc-rs folder and run `./target/debug/relayer -c ./relayer/relay/tests/config/fixtures/relayer_conf_example.toml query connection end chain_A connectionidone`

**Comment by adizere** [comment]
> Out of curiosity do they err if build with prost? It would be good to give that as feedback to the tendermint/sdk team.

No, they don't error, surprisingly. But note we had to manually copy/paste the gogo.proto from github into our repo..

It seems that only the prefix needs fixing. And we need to also define `pub struct CommitmentPrefix` which is empty. I'm now overhauling the code and will push an update soon with a simplified .proto versions. @andynog  please let me keep the token on your branch for a bit longer.

**Comment by ancazamfir** [comment]
> This is the output for the command above. Need someone (maybe @ancazamfir) to validate if it makes sense

Looks good! I made some comments in the PR wrt error handling. The command takes some other parameters, `-h <height>` for example queries at the specified height. I had `simd` running for longer and because of pruning the query at low heights fails with pages of traces. Same with non-existing connection.

**Comment by andynog** [comment]
Worked on the issue that an exception was thrown if height parameter was specified. Now it shows an error message (but not sure if the error makes sense, need @ancazamfir to validate message)

For example specifying height 4:

```
./target/debug/relayer -c ./relayer/relay/tests/config/fixtures/relayer_conf_example.toml query connection end chain_A connectionidone -h 4
     Options QueryConnectionOptions { connection_id: ConnectionId("connectionidone"), height: 4, proof: true }
connection query error RPC error: proof is unexpectedly empty; ensure height has not been pruned: invalid request
```
