### ISSUE TITLE
Relayer commands don't support help menu for subcommands

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/ibc-rs#134]
## Summary of Bug
When running `relayer query --help` I expect to see the list of subcommands but I just get:

```
$ relayer query --help
error: unrecognized command `--help`

relayer-cli 0.0.1
Anca Zamfir <anca@interchain.io>, Romain Ruetschi <romain@informal.systems>

FLAGS:
    -c, --config CONFIG       path to configuration file
    -h, --help                print help message
    -v, --verbose             be verbose

```

## Version

v0.0.1

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by andynog** [comment]
I've noticed this today when testing the query and mentioned on the group call. I'll take a look at that and ensure this works.

**Comment by andynog** [comment]
@ebuchman, I've done some investigation on this one. Haven't been able to solve it yet because was just trying to understand how abscissa works, and how it uses gumdrop for command line. I believe the way our code is currently implemented it should work (show usage for subcommands). Unfortunately the docs for abscissa and gumdrop are minimal on this topic. I'm more familiar with clap and structopt. 

But found some issues that might point that help usage for subcommands might be a limitation

- an old issue that might be related to this (it's closed but the current behaviour seems to point to this)
https://github.com/iqlusioninc/abscissa/pull/187

There are also a couple of issues open related to this

- upgrade gumdrop
https://github.com/iqlusioninc/abscissa/issues/250

- Or replace gumdrop with clap (I really like this idea, I found gumdrop to be very limited compared to clap)
https://github.com/iqlusioninc/abscissa/issues/298

**Comment by ebuchman** [comment]
Ah, looks like abscissa is going in the direction of clap. Maybe we should wait for / help with that. I guess we put this on hold until then?

**Comment by adizere** [comment]
Running this today (from targer/debug) works for me. The error message is gone.

```
adi@styx:ibc-rs $ target/debug/relayer --help
relayer-cli 0.0.1
Anca Zamfir <anca@interchain.io>, Romain Ruetschi <romain@informal.systems>

USAGE:
    relayer-cli <SUBCOMMAND>

SUBCOMMANDS:
    help       get usage information
    start      start the relayer
    listen     listen to IBC events
    config     manipulate the relayer configuration
    version    display version information
    query      query state from chain
    light      basic functionality for managing the lite clients
```

**Comment by andynog** [comment]
This works but I was talking about subcommands like `relayer query` should provide help context for the query subcommand. That doesn't work, currently it shows an error, it should show command usage
```
error: missing command name

relayer-cli 0.0.1
Anca Zamfir <anca@interchain.io>, Romain Ruetschi <romain@informal.systems>

FLAGS:
    -c, --config CONFIG       path to configuration file
    -h, --help                print help message
    -v, --verbose             be verbose
```

**Comment by andynog** [comment]
- Added logic to display some help messages. So if the user type a subcommand followed by the help keyword, usage will show, e.g.
    * `relayer query help`
    * `relayer query connection help`

But I haven't figure out a way to show a more complete usage information with parameters for example. I was exploring tmkms tool and it seems the help usage information is the same as what I've implemented. I think that gumdrop builtin options to show help messages are not as robust as clap. I hope that abscissa implements it.

**Comment by andynog** [comment]
got confirmation that indeed there's a bug in gumdrop v0.7 that doesn't show the parameters. I think this is the only solution for now until abscissa upgrades to gumdrop v0.8 or clap v3.

**Comment by ebuchman** [comment]
Ach ok let's drop it from this milestone for now then and wait for abscissa to upgrade (maybe we can even help with that)

**Comment by andynog** [comment]
Sure, I think if we are using it as a core framework for our cli apps we should find a way to help.

**Comment by andynog** [comment]
Will try to experiment replacing gumdrop with clap v3 in an [abscissa fork](https://github.com/informalsystems/abscissa) and see if that works.

**Comment by ancazamfir** [comment]
Looks like using `help` before the command works:
```
$ rrly help query client consensus
relayer-cli 0.0.3
Informal Systems <hello@informal.systems>

USAGE:
    relayer-cli query client consensus <OPTIONS>

DESCRIPTION:
    query client consensus

POSITIONAL ARGUMENTS:
    chain_id                  identifier of the chain to query
    client_id                 identifier of the client to query
    consensus_epoch           epoch of the client's consensus state to query
    consensus_height          height of the client's consensus state to query

FLAGS:
    -h, --height HEIGHT       the chain height which this query should reflect
    -p, --proof PROOF         whether proof is required
`

**Comment by ancazamfir** [comment]
Will move this to a later milestone, doesn't look like we get a fix from abscissa by end of month. Will keep an eye on it.

**Comment by andynog** [comment]
I don't think this is an issue anymore. I think it works using the `help` keyword before the command. It's just usually not the default to ask for help (most CLIs use `-h` or `--help` parameter) but there's a way to do it. And now that we have a Hermes guide that makes this clear I think we can close this issue if you agree @ancazamfir

**Comment by ancazamfir** [comment]
I guess it's ok to close this issue. But the pain point is not gone. It's very annoying to do `hermes help...`, figure out the command and then skip back to remove that. Also, is this something we make clear in the guide? I haven't searched it all, but I see in some cases we just show the usage, without including the `hermes help...` command that gave that output.

**Comment by colin-axner** [comment]
I support leaving this issue open. If I run `hermes keys` and see `unrecognized command` it can be quite confusing as a new user. 

We had a similar issue to this one a few years ago with gaia where cli interaction could prove troublesome due to unsupported features of the library we were using. As an intern I picked up the issue and made a quick hack to fix the UX issue. The feature is still unimplemented upstream after 2 years of requesting a fix. 

Leaving the issue open is useful as the painpoint is still there and perhaps in the future a new team member can come up with a reasonable hack in the meantime
