### ISSUE TITLE
Better handle insufficient gas/fees

### ISSUE THREAD

**Issue by gamarin2** [informalsystems/ibc-rs#1403]
## Crate

Hermes

## Summary

Hermes should automatically increase gas/gas-price in increments if out of gas/ insufficient fees errors are caught when trying to submit packet, up to a user-defined max. 

## Problem Definition

In the Cosmos SDK, the difference between `gasWanted` and `gasUsed` is not reimbursed. This means that if we configure hermes with `max-gas = 1000000` and `gas-price = 0.02uatom` for Cosmos Hub, we will always pay `20000uatom` per tx no matter how much gas we actually use. Because of this, we cannot set `max-gas` too high, or we end up paying absurd amounts of money to operate the relayer. The problem is that gas for IBC txs are not really predictable, and sometimes they go above the `max-gas` param. This in turn causes sequence issues and basically disruptions. 

## Proposal

When a relay tx fails to get submitted because of out-of-gas/insufficient fees error, hermes should retry with increased gas/gas-price (depending on the error). The increment value and absolute max should be user defined. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Note that there is a regression in Hermes #1354. Because of this problem, the `simulate` step fails. Hermes does this step to obtain an approximate amount of gas it should use for each tx (instead of using the `max_gas` preconfigured in config.toml).

Once we fix 1354 (aiming for release today), Hermes will use gas more thriftily. This used to be the default behavior pre-0.7.0. This means it will be safe to configure `max_gas` in Hermes config.toml to higher values, and those high values will only be used very rarely.

Would be curious if this solves the disruptions you have been seeing with your team, Gautier!

**Comment by gamarin2** [comment]
@adizere yes that should fix it! thanks

**Comment by gamarin2** [comment]
0.7.3 is a good fix
