### ISSUE TITLE
`tx_simulate` may fail with an empty error

### ISSUE THREAD

**Issue by romac** [informalsystems/ibc-rs#1454]
## Summary of bug

`tx_simulate` may apparently fail with an empty error, as can be seen in the logs below:

```
DEBUG ThreadId(59) send_messages_and_wait_check_tx with 2 messages
DEBUG ThreadId(59) [cosmoshub-4] send_tx: sending 2 messages using account sequence 35128
DEBUG ThreadId(59) [cosmoshub-4] default fee: Fee { amount: "40000uatom", gas_limit: 2000000 }
DEBUG ThreadId(59) [cosmoshub-4] simulated gas: Err(

                                                                                  vvvvvvvvvvvvvvv
ERROR ThreadId(59) [cosmoshub-4] failed to estimate gas, falling back on max gas, error:
                                                                                  ^^^^^^^^^^^^^^^

DEBUG ThreadId(59) [cosmoshub-4] send_tx: broadcast_tx_sync: Response { code: Ok, data: Data([]), log: Log("[]"), hash: transaction::Hash(2DCE205A1EB88678D518ECCDD0EF6CD49BAF2971526101EDBDEBD796F934E8EF) }
```

## Version

v0.7.3

## Steps to Reproduce

TBD

## Acceptance Criteria

TBD

____

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
This seems to have been fixed by adding the `e.detail` to the log output.

Previously we were logging with:
https://github.com/informalsystems/ibc-rs/blob/5d53e5279d765024913494a129c55e9bf780c409/relayer/src/chain/cosmos.rs#L255-L258

Versus the current approach:

https://github.com/informalsystems/ibc-rs/blob/8212fc8ebaa0a51fb45bc04cc656f42eab1cee68/relayer/src/chain/cosmos.rs#L356-L359
