### ISSUE TITLE
Account sequence errors from connecting to partially synced chains

### ISSUE THREAD

**Issue by faddat** [informalsystems/ibc-rs#1462]
## Crate

relayer-cli

## Summary of Bug

If hermes is started while a chain is syncing, it picks up old acccount sequence values, and then attempts to use them repetitively.  

The temporary solution is "don't start hermes against a partially synced chain"

The permanent solution is probably to actively check the account sequence 

## Version

0.7.3 + the compatiblity pr https://github.com/informalsystems/ibc-rs/pull/1461

## Steps to Reproduce

Heheh, little bit of a hard one here, but I guess it's approximately:

Using a wallet that has already been used for relaying, start Hermes against a partially synced Juno or Sifchain.    What is likely to occur here is that Hermes will keep trying to make a tx with an invalid sequence number.  

Another solution to this may be to disable hermes from interacting with partially-synced chains.  

## Acceptance Criteria

It should no longer be possible for Account sequence issues to crop up because it was connected to partially-synced chains from a previously used wallet.  
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Hey Jacob,

This is a tough one! In general, Hermes cannot trust account sequence numbers from a full node unless that node (a) is synced with the network and (b) has a clean mempool ([ref](https://github.com/informalsystems/ibc-rs/issues/1264#issuecomment-923095155)). For (b) we don't have a solution yet, but we're working with tm-go team to find one. The problem you're highlighting here is in reference to case (a).

With respect to (a) it's not clear how can Hermes reliably infer whether the node is or isn't synced with the network. For SDK-based chains there is the option to query the node's status endpoint and read the `catching_up = true` field; if `false` then the node is clearly not synced; if `true` then it's actually not clear what the status is, because the node may be out of sync and be unaware (the `true` flag is unreliable).

Beside the `catching_up` flag, is there any API that Hermes can use to infer if the full node is synced or not? Any insights appreciated!

**Comment by MasterPi-2124** [comment]
Hi @adizere, thank you for your comment! We checked our chains, in this case, Juno, and it's unsynced with `catching_up=false`, but other chains are unsynced too, and they are still healthy.

**Comment by adizere** [comment]
This problem has been partly solved in PR #1349, which closed a related issue #1264.

> Another solution to this may be to disable hermes from interacting with partially-synced chains.
Currently Hermes either

> It should no longer be possible for Account sequence issues to crop up because it was connected to partially-synced chains from a previously used wallet.

Currently, Hermes either:
- detects that a chain is out of sync via the health checkup (namely, the parameter `catching_up`), and in that case it emits a clear warning that some functionality is impacted.
- does not detect the out of sync problem, but encounters an account sequence mismatch error and has an built-in mechanism to recover (by retrying) from that, thanks to the work in #1349.
    - operators __no longer need to restart Hermes, but they may need to restart their full node__ if Hermes is unable to make progress due to the account sequence mismatch error.

I will therefore close this issue, and we may consider reopening if we still see problem in the future.
