### ISSUE TITLE
max_tx_size is greater than 90% of the genesis block param max_size

### ISSUE THREAD

**Issue by RohitAudit** [informalsystems/ibc-rs#1604]
## Crate

relayer

## Summary of Bug

I am running a relayer between cosmos chain and persistence chain. I have been facing 2 issues from quite some time.

1. I have put max_tx_size in config to be 190000 but still this issue occurs for both persistence and cosmos chain.
```
2021-11-23T04:46:05.068655Z  WARN ThreadId(01) [core-1] chain is unhealthy: 
   0: semantic config validation failed for option `max_tx_size` chain 'core-1', reason: `max_tx_size` = 190000 is greater than 90% of the genesis block param `max_size` = 200000

Location:
   /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/flex-error-0.4.4/src/tracer_impl/eyre.rs:10

```
2. The relayer works fine when started when starts throwing errors after sometime.

```
Nov 23 04:42:34.202  INFO ThreadId(38) [core-1:transfer/channel-7 -> cosmoshub-4] generate messages from batch with 1 events
Nov 23 04:42:34.203 ERROR ThreadId(38) [core-1:transfer/channel-7 -> cosmoshub-4] worker: handling command encountered error: 
   0: failed during query to chain id cosmoshub-4
   1: failed to send through channel

Location:
   /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/flex-error-0.4.3/src/tracer_impl/eyre.rs:10

```

```
hermes[2143593]: Nov 22 12:24:08.310  INFO ThreadId(717) [core-1:transfer/channel-7 -> cosmoshub-4] clearing pending packets height=Some(Height { revision: 1, height:>
hermes[2143593]: Nov 22 12:24:08.833 ERROR ThreadId(717) [core-1:transfer/channel-7 -> cosmoshub-4] worker: handling command encountered error:
hermes[2143593]:    0: clearing of old packets failed
hermes[2143593]: Location:
hermes[2143593]:    /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/flex-error-0.4.3/src/tracer_impl/eyre.rs:10
hermes[2143593]: Backtrace omitted.
hermes[2143593]: Run with RUST_BACKTRACE=1 environment variable to display it.
hermes[2143593]: Run with RUST_BACKTRACE=full to include source snippets. path=packet::channel-7/transfer:core-1->cosmoshub-4
```
## Version

version 7 and 8

## Acceptance Criteria

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Thanks for reporting this issue.

> version 7 and 8

Some of these health checks have been changed, please consider upgrading Hermes to the [latest version](https://github.com/informalsystems/ibc-rs/releases). It's possible that both of the issues you highlighted have been fixed in the meantime.

I'll provide a bit more context.

> I have put max_tx_size in config to be 190000 but still this issue occurs for both persistence and cosmos chain.
> 2021-11-23T04:46:05.068655Z  WARN ThreadId(01) [core-1] chain is unhealthy: 
   0: semantic config validation failed for option `max_tx_size` chain 'core-1', reason: `max_tx_size` = 190000 is greater than 90% of the genesis block param `max_size` = 200000


The chain 'core-1' will not accept transactions over '200000' bytes in size. You should consider using a smaller `max_tx_size` for Hermes config.toml, otherwise the transactions Hermes tries to submit will starve.


> hermes[2143593]:    0: clearing of old packets failed
> ...
>    0: failed during query to chain id cosmoshub-4
   1: failed to send through channel

This is an internal error (the channel is not an IBC channel). Probably one of the execution threads has died and that thread cannot be reached anymore by the other threads. Given the context in the logs, it's difficult to diagnose the problem in more detail. 

Are you still encountering these errors in 0.9.0? In particular we'd be curious to see more log context for the problem with `clearing of old packets failed`.

**Comment by RohitAudit** [comment]
Let me update the relayer the relayer to the latest version and will get back to you with the stacktrace if the issue persists

**Comment by adizere** [comment]
Closing as probably outdated. Please reopen if you uncover more details that can help us track down the problem.
