### ISSUE TITLE
"supervisor was not able to connect to any chains" message spamming

### ISSUE THREAD

**Issue by reuvenpo** [informalsystems/ibc-rs#1605]
## Crate

Hermes CLI (afaik)

## Summary of Bug
We have several relayer that we have set up between [Secret Network](https://scrt.network/) and other chains, and in all of them our hermes logs keep getting spammed with these sorts of messages about chains that aren't related to the chains that the hermes instance is configured to listen on (and we use appropriate channel filters).

The error looks like this on hermes v0.8.0: (removed timestamps)
```
Caused by:
    missing chain for id (osmosis-1) in configuration file
Location:
    /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/flex-error-0.4.4/src/tracer_impl/eyre.rs:10:9
ERROR ThreadId(01) [secret-4] error during batch processing: supervisor was not able to connect to any chains
```

And like this on v0.9.0:
```
ERROR ThreadId(01) [cosmoshub-4] error during batch processing: supervisor was not able to connect to any chains: missing chain for id (osmosis-1) in configuration file
```

## Version

v0.8.0 and v0.9.0

## Steps to Reproduce

Set up a v0.8.0 or v0.9.0 relayer between secret-4 and cosmoshub-4

## Acceptance Criteria

Make the voices go away :(

____

## For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by romac** [comment]
Thanks for the bug report!

First, the error message is wrong because of a typo in the relayer code, it should read: `unable to spawn chain runtime for chain 'osmosis-1'` instead of `supervisor was not able to connect to any chains `.

Now this specific error you are seeing may happen when the relayer tries to relay a packet to/from a chain that it is not configured to connect to, which should not happen if the packet filter is properly configured.

Any chance you could run the relayer with `log_level = "trace"` and share both an excerpt from the logs as well as your configuration file, here or privately, so that we can a closer look? This would hopefully let us figure out whether this is a configuration problem or a bug in the relayer.

**Comment by reuvenpo** [comment]
@romac Sorry for the slow response, I was handling other tasks over the last few days.

Apparently I forgot to turn on channel filtering - I set the configuration for it but forgot to enable `mode.packets.filter = true` 😅 

Thanks! This is resolved now.
