### ISSUE TITLE
Make the relayer CLI and library top-level folders

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/ibc-rs#180]
## Summary
It's a bit confusing that the `relayer` and the `modules` are top-level libraries and although `modules` is a crate in its own right, the `relayer` has a `cli` subfolder and a `relay` subfolder which are their own crates.

Also #167 the name of the modules crate is weird.

## Proposal
All crates should be top-level folders in the repo. Namely:

modules
relayer-cli
relayer
(ibc-proto as of #142 )

Alternatively (and in line with #142) all should have the `ibc-` prefix. That would make the naming for the crates (#167) also clear.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by andynog** [comment]
I like the suggested re-org of the folders. More inline with tendermint-rs that has the crates as top-level. But we should just to plan it accordingly since this is a major refactoring just need to bear in mind what the best workflow for this concerning merges and PRs. The work effort here is not big but has to be the least disruptive as possible to parallel development. Maybe integrate this just before the next release?

**Comment by greg-szabo** [comment]
I wouldn't wait until the next release, since we didn't release this library yet, as far as I know.

The sweet spot is when there is no ongoing soon-to-be-merged work in the repo. I'm aware of Andy's work on connections that is soon-to-be-merged, but everything else we work on right now seems fairly experimental and higher-level. And most importantly, full of new files. My proposal is that we do this right after Andy's client query work is done, to try to minimize the pain for any other ongoing work.

**Comment by greg-szabo** [comment]
Ok, this is happening after Andy's PR. Here's the proposed naming:

modules
relayer-cli
relayer
(proto)

I suggest #167 use the `ibc-` prefix for crate names but we can discuss it there.
