### ISSUE TITLE
Develop Gaia fork with ICS29 Fee Middleware enabled

### ISSUE THREAD

**Issue by soareschen** [informalsystems/ibc-rs#1967]
## Summary

Try to create our own Gaia fork that uses https://github.com/cosmos/ibc-go/pull/276 and release it on Cosmos.nix. This would only be worthwhile if there is not too much work needed to modify the existing Gaia source code. The work may be much smoother if there is already a Gaia branch that targets ibc-go master or ibc-go v3, which unfortunately doesn't appear to be present.

With this Gaia fork, we will be able to perform integration test on the fee middleware before it gets released. Otherwise we can only delay the testing and development until a proper version of Gaia is available.

Meanwhile, we can still start some development in the blind without testing support, at the risk of significant changes might be required depending on the official release.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Closing this depends on https://github.com/cosmos/ibc-go/issues/1162.


It seems that we are headed towards a two-phase process:

1. As suggested in https://github.com/cosmos/ibc-go/issues/1162, during early phases of development of an IBC-go feature, we would get easy access to that feature by employing `simapp`. The IBC-go team believe this is the most appropriate way for them to give access to feature for relayer teams.

3. As the feature matures, it is expected to eventually land in a Gaiad RC. Example: [Gaia-v7-rc0](https://github.com/cosmos/gaia/releases/tag/v7.0.0-rc0) one is a ICA-enabled Gaia RC. This RC is obviously coming out too late for the relayer team to test and develop with, so we have used instead https://github.com/cosmos/interchain-accounts-demo.


For our team, this essentially means we want to develop more support for running tests on `simapp`, instead of gaiad. (Additionally, I can imagine relying increasingly more on the Gaia team to test their own releases against Hermes, while our team ensures cutting edge features testing with `simapp`).

**Comment by romac** [comment]
Just to clarify on point 2, the issue with Gaia 7 is not that the RC came too late for us to test with it but rather that it does not come with the controller module enabled, cf. an internal message from the Go team:

> Gaia v7.0.0-rc0 has only the host submodule for interchain accounts enabled. So to use it with the demo on the readme wouldn’t be possible, as you need a controller chain to register an account and send txs.

**Comment by soareschen** [comment]
I have tried the suggestion in https://github.com/cosmos/ibc-go/issues/1162 and tested the integration test CI with the `simapp` in #1996 and they do seem to work. So this issue can be closed once #1996 is merged.
