### ISSUE TITLE
Relaying of packets slows down exponentially if many channels are created after the relayer

### ISSUE THREAD

**Issue by soareschen** [informalsystems/ibc-rs#1978]
## Summary of Bug

If many new channels are created after the relayer supervisor is spawned, the relaying of packets seem to slow down exponentially. This does not applies if the channels are created _before_ the supervisor is spawned.

## Steps to Reproduce

PR #1977 provides a test case `test_slow_ternary_ibc_transfer` that runs very slowly with the supervisor spawned before the channels are created. The original test `test_ternary_ibc_transfer` demonstrates that the test finishes much faster if the supervisor is spawned after the channels are created.

## Acceptance Criteria

The test cases `test_slow_ternary_ibc_transfer` and `test_ternary_ibc_transfer` in #1977 should take roughly the same time to finish.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
@ancazamfir managed to reproduced this with 3 chains, whether or not channels are spawned before or after the supervisor.  `git bisect` points to the first commit in #1656. Still unclear what exactly is going on.

**Comment by romac** [comment]
We are both seeing that the SendPacket event is coming super late through the WebSocket, everything after that is super quick. Not clear what this has to do with #1656 since it does not even touch the event monitor.

**Comment by soareschen** [comment]
It could be because #1656 does the refactoring of the original code, so you kind of track it manually before that commit.

I suspect it might be misuse of retry logic somewhere with an exponential back off mechanism. That might be why the events are processed slower and slower as the number of channels increases, even though the CPU is mostly idle.

**Comment by romac** [comment]
The cause of slowness was that the height of the events we were pulling from the subscriptions would drift exponentially from the real latest height, because we were not pulling them from the event monitor stream fast enough.

We were trying to get an event from the stream of events (with `try_recv_multiple`) every 500ms.

So with two chains we have:
- call try_recv_multiple and get a NewBlock from chain A
- wait 500ms
- call try_recv_multiple and get a NewBlock from chain B
- wait 500ms
- call try_recv_multiple and get a NewBlock from chain A
etc.

So we get an event per chain roughly once every second.


With three chains:

- call try_recv_multiple and get a NewBlock from chain A
- wait 500ms
- call try_recv_multiple and get a NewBlock from chain B
- wait 500ms
- call try_recv_multiple and get a NewBlock from chain C
- wait 500ms
- call try_recv_multiple and get a NewBlock from chain A
- etc.

So we were getting a NewBlock event per chain every 1.5s.

But since the block time for testing is 1s, we end up drifting behind more and more.
I guess that's why we only see this in testing and not in prod, because in prod we query often enough that we are always up to date.


The problem gets worse the lower the block time and the higher the number of chains the relayer is connected to.

To fix this, we now use a blocking `recv_multiple` on the subscriptions stream so that we get the events as fast as they are emitted, which solves the drift.
