### ISSUE TITLE
Conflict between `gas_multiplier` and `gas_adjustment`

### ISSUE THREAD

**Issue by AlianBenabdallah** [informalsystems/ibc-rs#2398]
## Summary of Bug

Running with `--config` flag expects `gas_multiplier` while other commands expect `gas_adjustment`

Using `gas_multiplier = 2`,  `hermes tx raw create-client ibc-1 ibc-0` throws : hermes tx raw create-client ibc-1 ibc-0
## Version

hermes 1.0.0
gaia 4.2.1

## Steps to Reproduce

Create a config file with `gas_adjustment = 1.0` instead of `gas_multiplier`

```
cargo run -q --bin hermes -- --config "$CONFIG_FILE" keys add --chain "$CHAIN_0_ID" --key-file "$GAIA_DATA/$CHAIN_0_ID/user_seed.json"` (command used by `ibc-rs/scripts/init-hermes`) 
```

should throw : 

```
error: hermes fatal error: config error: config file specifies deprecated setting gas_adjustment = 1` for the chain 'ibc-0'; to get the same behavior, use `gas_multiplier = 2`
```

Then replace `gas_adjustment` by `gas_multiplier`

```
hermes tx raw create-client ibc-1 ibc-0
```

throws : 

```
The Hermes configuration file at path '~/.hermes/config.toml' is invalid, reason: parse error: unknown field `gas_multiplier`, expected one of `id`, `rpc_addr`, `websocket_addr`, `grpc_addr`, `rpc_timeout`, `account_prefix`, `key_name`, `key_store_type`, `store_prefix`, `default_gas`, `max_gas`, `gas_adjustment`, `fee_granter`, `max_msg_num`, `max_tx_size`, `clock_drift`, `max_block_time`, `trusting_period`, `memo_prefix`, `proof_specs`, `trust_threshold`, `gas_price`, `packet_filter`, `address_type` for key `chains` at line 239 column 1
```

## Acceptance Criteria

Every command only expects `gas_adjustment` or `gas_multiplier`

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
What's happening here is that when you do not pass the `--config FILE` option, Hermes will load the configuration from `~/.hermes/config.toml` instead of `FILE`.

In your case, it seems that the config file at  `~/.hermes/config.toml` still mentions the now deprecated `gas_adjustment` setting. To fix this you should be able to switch from `gas_adjustment` to `gas_multiplier` in that config file, or just always pass the `--config FILE` option with a path to a valid/up-to-date configuration file.

**Comment by romac** [comment]
From private chat: the issue is that binary in the second command is outdated. That stems from the fact that `cargo install ibc-relayer-cli` (as per the guide) will install Hermes 0.15.0 instead of 1.0.0-rc.0 as the latter is a pre-release. We need to update the guide to fix the Cargo installation step.
