### ISSUE TITLE
About the use of WriteAcknowledgement

### ISSUE THREAD

**Issue by DaviRain-Su** [informalsystems/ibc-rs#2424]
I found the handling of `writeAcknowledgement` in the read [spec](https://github.com/cosmos/ibc/tree/master/spec/core/ics-004-channel-and-packet-semantics#writing-acknowledgements), and it seems that there is no handling of `writeAknowledgement` in ibc-rs

## Summary of Bug

- This is ics04channel packet_callback, This no deal with WriteAcknowledgement : https://github.com/informalsystems/ibc-rs/blob/a189902e6f1d726e22bfe394134dba44a2e0f653/modules/src/core/ics04_channel/handler.rs#L206
- In Applications/transfer, also no deal with this: https://github.com/informalsystems/ibc-rs/blob/a189902e6f1d726e22bfe394134dba44a2e0f653/modules/src/applications/transfer/context.rs#L204

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by hu55a1n1** [comment]
Nice catch @DaviRain-Su! ibc-rs indeed does not handle the synchronous case for `writeAcknowledgement`. :+1: 
I think the best place to implement this would be in the `crate::core::ics04_channel::handler::packet_callback` after these lines (similar to [how ibc-go does it](https://github.com/cosmos/ibc-go/blob/193e41480dc8a8994902d14b9f13d72a23df2734/modules/core/keeper/msg_server.go#L422)) -> https://github.com/informalsystems/ibc-rs/blob/a189902e6f1d726e22bfe394134dba44a2e0f653/modules/src/core/ics04_channel/handler.rs#L209-L213
Here's a related issue -> https://github.com/informalsystems/ibc-rs/issues/1525
Would you like to take a stab at fixing this? Happy to help review and merge it. Otherwise will fix this before the next release.

**Comment by hu55a1n1** [comment]
Related issue/bug -> #2428.

**Comment by DaviRain-Su** [comment]
> 

I have do a pr
