### ISSUE TITLE
Duplicate protos between ibc-rs and tendermint-rs

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/ibc-rs#284]
# Summary of Bug
Some IBC proto files (e.g. `ibc.tendermint.rs::Header`) need to reference some other proto files and structures (e.g. `tendermint.types.rs::SignedHeader` or `tendermint.types.rs::ValidatorSet`) that belong to tendermint-rs where we expect the conversions between raw and domain types are implemented. 
Presently the ibc-proto files point to duplicate tendermint files in ibc-proto, in particular `tendermint.types.rs` for the examples above. But I believe all `tendermint` files in IBC proto are dups of the ones in `tendermint-rs`

## Version
master

## Steps to Reproduce

____

## For Admin Use

- [X] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
This is blocking progress for https://github.com/informalsystems/ibc-rs/issues/277 where I get errors like:

^^^^ the trait `std::convert::From<ibc_proto::tendermint::types::SignedHeader>` is not implemented for `tendermint::block::signed_header::SignedHeader`

I would expect at most something like:
^^^^ the trait `std::convert::From<tendermint_proto::types::SignedHeader>` is not implemented for `tendermint::block::signed_header::SignedHeader`
if the conversion is not implemented yet in tendermint-rs.

**Comment by greg-szabo** [comment]
The problem is that the Cosmos SDK is copying Tendermint messages from the Tendermint repository's protobuf message folder. Here's a note claiming that: https://github.com/tendermint/tendermint/blob/10f30f8a995d058a76f5f2c5b1ec809f58e8464a/proto/tendermint/abci/types.proto#L15

Because we compile the messages separately in Prost, the IBC Prost compiler doesn't know about a separate set of messages in the Tendermint repository and compiles them as it sees it.

We have to figure out if we can merge the two protobuf message folders together either at the source or during compilation into Rust structs. Or as a third option, somehow separate the Tendermint-related messages in the Cosmos SDK.
I'm not sure, but the copy of Tendermint messages is definitely problematic.

**Comment by greg-szabo** [comment]
#292 solves the problem but it requires a rebuild of the IBC protobuf files.
