### ISSUE TITLE
Help and usage show wrong executable name 'ibc-relayer-cli` 

### ISSUE THREAD

**Issue by andynog** [informalsystems/ibc-rs#590]
## Crate

ibc-relayer-cli

## Summary of Bug

When I compile the ibc-relayer-cli crate it generates an executable called `hermes` but if I run it, when the help message is displayed, `hermes` is not shown but `ibc-relayer-cli` which might be confusing to the end user.

```shell
$ ./target/release/hermes 
ibc-relayer-cli 0.1.0
Informal Systems <hello@informal.systems>

USAGE:
    ibc-relayer-cli <SUBCOMMAND>

SUBCOMMANDS:
    help       get usage information
    start      start the relayer (currently this refers to the v0 relayer)
    channel    channel functionality for managing channels
    listen     listen to IBC events
    config     manipulate the relayer configuration
    version    display version information
    query      query state from chain
    tx         create IBC transactions on configured chains
    light      basic functionality for managing the lite clients
    keys       manage keys in the relayer for each chain
```

## Version

v0.1.0

## Steps to Reproduce

Build and run
____

## For Admin Use

- [X] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
I looked into this and renaming the content of the help message seems difficult. This is because abscissa uses by default the package name (instead of binary name) to create all usage and help messages:

Some pointers:
- under the hood, when we run `./target/release/hermes` what we actually run is an `abscissa_core::EntryPoint`, parametrized with `CliCmd`:

https://github.com/informalsystems/ibc-rs/blob/9d0a7b8f11a252e68e039a976910edd33107f074/relayer-cli/src/application.rs#L60

- the `EntryPoint` [inherits its `name` field](https://github.com/iqlusioninc/abscissa/blob/82787669c61a371cfab634ba5520f698b6d1e4a2/core/src/command/entrypoint.rs#L62) (which is used in all usage/help messages) from `CliCmd::name()`

- `CliCmd` has its `name` setup by a derive: `#[derive(Command..` 

https://github.com/informalsystems/ibc-rs/blob/93c0e6d4342696523adbde4ea57f4e2c3965b6a2/relayer-cli/src/commands.rs#L35-L37

- the derive `Command` macro is [defined here](https://github.com/iqlusioninc/abscissa/blob/82787669c61a371cfab634ba5520f698b6d1e4a2/derive/src/command.rs#L19), which assigns the `env!("CARGO_PKG_NAME")`  as `name` to any command.

**Comment by romac** [comment]
Yeah Abscissa should use `CARGO_BIN_NAME` instead of `CARGO_PKG_NAME`.

We can try [overriding](https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-envvarvalue) the `CARGO_PKG_NAME` env variable in `build.rs` but that may break a bunch of stuff.
