### ISSUE TITLE
Hermes failing to compile

### ISSUE THREAD

**Issue by Fraccaman** [informalsystems/ibc-rs#672]
## Crate
- ibc-relayer-cli

## Summary of Bug

Following the guide [here](https://hermes.informal.systems/installation.html#building-with-cargo-build), building `hermes` either from source or using cargo, leads to compile errors.
Here the error logs: [pastebin](https://pastebin.com/jvDapyBr)

## Version
- cargo: `cargo 1.50.0 (f04e7fab7 2021-02-04)`
- rustc: `rustc 1.50.0 (cb75ad5db 2021-02-10)`
- hermes: `v0.1.0`

## Steps to Reproduce

- `cargo install ibc-relayer-cli`

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Hi, thank you for opening this issue.

Intuitively, the problem is that an indirect dependency (`funty`) of crate `ibc-relayer-cli` had a minor-version update recently, which [is causing build errors](https://github.com/informalsystems/ibc-rs/issues/665) in release `v0.1.0`. We have solved this problem, but did not release a new version since then.

The simplest way to mitigate this would be to build Hermes from source -- as documented in [here](https://hermes.informal.systems/installation.html#build-from-source), __but ignore the following step:__

```
git checkout v0.1.0
```

Instead, no need to check-out any specific release (just use `master`, the default version that is checked-out when you clone the repo).

**Comment by Fraccaman** [comment]
Okay, thanks! On `master` is compiling without any error.

**Comment by adizere** [comment]
Great!

We will update the documentation shortly to mention this problem & workaround explicitly.
