### ISSUE TITLE
Rework `ibc::ics04_channel::events` module

### ISSUE THREAD

**Issue by romac** [informalsystems/ibc-rs#718]
## Crate

`ibc`

## Summary

The various channel events defined in the `ibc::ics04_channel::events` module are all defined as newtypes over the same `Attributes` which has some optional fields which are expected to always be defined for specific events. As such, this forces us to `unwrap` these values in [some places](https://github.com/informalsystems/ibc-rs/pull/692#discussion_r583791447). We should refactor this module to perform this check when parsing the source event, and perhaps refactor the parsing code a little bit while we're at it.
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by Wizdave97** [comment]
@romac  I've made a draft implementation here https://github.com/Wizdave97/ibc-rs/blob/david/rework-channel-events/modules/src/core/ics04_channel/events.rs, I want to know if that's on track, especially the use of `TryFrom<Attributes>` instead of `From<Attributes>` since the other events still use optional `channel_id` values,  or do I enforce existence of `channel_id` on all other events?
