### ISSUE TITLE
Clarify Cosmos SDK minimum version requirements for Hermes

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#896]
## Crate

`ibc-relayer-cli`

## Summary

There's various chains built on top of the SDK at different versions.
We should clarify which version of SDK is Hermes (at a particular `v`) expected to work seamlessly.

## Acceptance Criteria
- [ ] Update the guide with clear version ranges for the SDK

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by greg-szabo** [comment]
I'm still having issues running the e2e testing script, I can't interpret some of the output (the script exits with exit code 1 but no errors). I assume that the expected output of 4.2.1 is correct and I'm now comparing outputs from different gaiad network executions. Here are the results so far:

```
| Binary version | SDK version | Compatible (most probably, need to confirm test results)
| 4.2.1          | 0.42.4      | Y
| 4.2.0          | 0.42.3      | Y
| 4.1.2          | 0.42.2      | Y
| 4.1.1          | 0.42.2      | Y
| 4.1.0          | 0.42.0      | Y
| 4.0.6          | 0.42.0      | Y
| 4.0.5          | 0.41.4      | Y
| 4.0.4          | 0.41.3      | Y
| 4.0.3          | 0.41.3      | Y
```

**Comment by ancazamfir** [comment]
> I'm still having issues running the e2e testing script, I can't interpret some of the output (the script exits with exit code 1 but no errors)

Can you paste the output when the script exits with 1?

**Comment by greg-szabo** [comment]
I couldn't really parse the output because of all the extra logs afterwards.

It turned out to be multiple issues:
* The `hermes start` command adds a lot of output to the screen with litreally no use. Even if hermes fails and outputs an error, the script continues. Solution: redirect the stdout and stderr to `os.DEVNULL` in the script.
* Hermes 0.3.2 is not compatible with the e2e script because of the changes in the start/start-multi command. Solution: upgrade to a hermes binary built from master. Note: the hermes config needed updates because of the telemetry parameters. If those params are missing, hermes panicked.
* the default 300000 gas was too small in some cases. The script tries to run the transaction, hermes fails and the script skims over it and continues to run. Usually, you end up failing further down the path when, for example, the number of acknowledged transactions is not the same as the number of sent transactions. Solution: set higher gas in the hermes config.
* After starting hermes, the script waits a bit and checks if all pending transactions were sent. In multiple cases the script reported that there are still pending transactions, the queue is not empty. Solution: raise the `sleep()`s in the code (in two places) from the 10-second wait time to 30 seconds. (20 seconds was still too fast)
* The original issue at startup was that after creating the channel, the script couldn't query it, and even with retries, it failed. Solution: add a `sleep(2.0)` into the retries (possibly this was a mistake that it was completely missing, so the retries finished too early).

With that said, the above table is now confirmed to pass the e2e testing. Additionally, I've tested a scenario where one chain was on the latest `4.2.1` version of gaiad while the other was on the earliest `4.0.3` version and the e2e testing succeeded in that scenario too.

We can try additional in-between versions but I think the basics are covered, except for misbehaviour handling.

**Comment by ancazamfir** [comment]
> Solution: raise the sleep()s in the code (in two places) from the 10-second wait time to 30 seconds. (20 seconds was still too fast)

We should poll every 1-2 secs up to a maximum instead. There are a few tests that already use this but we didn't make the changes everywhere. Partly because we are hoping to move from python to Rust so we build smarter tests.

**Comment by adizere** [comment]
This issue was covered by: https://github.com/informalsystems/ibc-rs/pull/1028/files#diff-4d03365b3d28de0e357752afa91dcec8b57eb23acc0ef4def5a7aa56bf7fd7f5
